server:
  port: 8002

mybatis:
  type-aliases-package: com.ycz.springcloud.pojo
  mapper-locations: mybatis/mapper/*.xml
  #开启二级缓存
  configuration:
    cache-enabled: true

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: org.gjt.mm.mysql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: com.ycz.springcloud-provider-dept8002

info:
  app.name: com.ycz.springcloud
  company: blog.kuangstudy.com
